### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by REPH26** [seamusleahy/ACF-PHP-Recovery#7]
Were to include my php file that contain the fields to recover?

**Comment by seamusleahy** [comment]
Just include the PHP field definition as you would if you were using it in production. Most people copy the PHP code and then place it within their theme's `functions.php` file.

The directions on ACF have you save the file in your them folder as `<your theme folder>/acf/acf.php` and then include them from your `functions.php` by:

```php
<?php
// ... the rest of the file
include_once( get_stylesheet_directory() . '/acf/acf.php' );

?>
```
http://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/
